/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as SetupRouteImport } from './app/setup'
import { Route as LeaderboardRouteImport } from './app/leaderboard'
import { Route as DrawRouteImport } from './app/draw'
import { Route as CampaignsRouteImport } from './app/campaigns'
import { Route as AuthRouteImport } from './app/auth'
import { Route as IndexRouteImport } from './app/index'
import { Route as ClaimPublicCodeRouteImport } from './app/claim/$publicCode'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DrawRoute = DrawRouteImport.update({
  id: '/draw',
  path: '/draw',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsRoute = CampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimPublicCodeRoute = ClaimPublicCodeRouteImport.update({
  id: '/claim/$publicCode',
  path: '/claim/$publicCode',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/campaigns': typeof CampaignsRoute
  '/draw': typeof DrawRoute
  '/leaderboard': typeof LeaderboardRoute
  '/setup': typeof SetupRoute
  '/claim/$publicCode': typeof ClaimPublicCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/campaigns': typeof CampaignsRoute
  '/draw': typeof DrawRoute
  '/leaderboard': typeof LeaderboardRoute
  '/setup': typeof SetupRoute
  '/claim/$publicCode': typeof ClaimPublicCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/campaigns': typeof CampaignsRoute
  '/draw': typeof DrawRoute
  '/leaderboard': typeof LeaderboardRoute
  '/setup': typeof SetupRoute
  '/claim/$publicCode': typeof ClaimPublicCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/campaigns'
    | '/draw'
    | '/leaderboard'
    | '/setup'
    | '/claim/$publicCode'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/campaigns'
    | '/draw'
    | '/leaderboard'
    | '/setup'
    | '/claim/$publicCode'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/campaigns'
    | '/draw'
    | '/leaderboard'
    | '/setup'
    | '/claim/$publicCode'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CampaignsRoute: typeof CampaignsRoute
  DrawRoute: typeof DrawRoute
  LeaderboardRoute: typeof LeaderboardRoute
  SetupRoute: typeof SetupRoute
  ClaimPublicCodeRoute: typeof ClaimPublicCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/draw': {
      id: '/draw'
      path: '/draw'
      fullPath: '/draw'
      preLoaderRoute: typeof DrawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns': {
      id: '/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof CampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claim/$publicCode': {
      id: '/claim/$publicCode'
      path: '/claim/$publicCode'
      fullPath: '/claim/$publicCode'
      preLoaderRoute: typeof ClaimPublicCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CampaignsRoute: CampaignsRoute,
  DrawRoute: DrawRoute,
  LeaderboardRoute: LeaderboardRoute,
  SetupRoute: SetupRoute,
  ClaimPublicCodeRoute: ClaimPublicCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
